development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  database: <%= ENV['DATABASE_URL'] %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: Project_production
